# Generated by Django 5.1.5 on 2025-02-01 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_profile_image_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completionrate',
            name='profile',
        ),
        migrations.AddField(
            model_name='completionrate',
            name='completion_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completion_rate', to='users.completionstats', verbose_name='Completion Stats'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=50),
        ),
    ]
