# Generated by Django 5.1.5 on 2025-02-01 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_completionrate_completion_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completionrate',
            name='completion_stats',
        ),
        migrations.AddField(
            model_name='completionrate',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completion_rate', to='users.profile'),
        ),
    ]
