# Generated by Django 5.1.5 on 2025-02-01 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_completionrate_completion_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completionrate',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_rate', to='users.profile'),
        ),
    ]
