# Generated by Django 5.1.5 on 2025-02-01 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_completionrate_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completion_rate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_completion_rate', to='users.completionrate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completion_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_completion_stats', to='users.completionstats'),
        ),
        migrations.AlterField(
            model_name='completionrate',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_rate_profile', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='completionstats',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_stats_profile', to='users.profile'),
        ),
    ]
