# Generated by Django 5.1.5 on 2025-02-01 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_completion_rate_profile_completion_stats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='completion_stats',
        ),
        migrations.AlterField(
            model_name='completionstats',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_stats', to='users.profile'),
        ),
    ]
