# Generated by Django 5.1.5 on 2025-01-28 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_datetime_reminder_reminder_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['reminder_datetime']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='task',
            field=models.ForeignKey(default='ac99b1c1-fd42-473c-8efb-4a1dfff40555', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.task'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['reminder_datetime', 'is_completed'], name='api_reminde_reminde_b34ad5_idx'),
        ),
    ]
