# Generated by Django 5.1.5 on 2025-01-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_reminder_options_reminder_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.task'),
        ),
    ]
