# Generated by Django 5.1.5 on 2025-01-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reminder_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='user_timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
