# Generated by Django 5.1.5 on 2025-01-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reminder_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='user_timezone',
        ),
    ]
